name: Attack Atlas Worker
on:
  workflow_dispatch:
    inputs:
      task_batch:
        description: 'JSON array of task IDs to process'
        required: true
      provider_id:
        description: 'Provider instance ID for tracking'
        required: true
      batch_id:
        description: 'Unique batch identifier'
        required: true

jobs:
  worker:
    runs-on: ubuntu-latest
    timeout-minutes: 360
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: docker/login-action@v3
        with:
          username: drkace
          password: ${{ secrets.DOCKER_PAT }}
          registry: docker.io

      - name: Run Worker in Docker
        run: |
          docker run --rm \
            -e GITHUB_ACTIONS="true" \
            -e BATCH_MODE="true" \
            -e TASK_BATCH="${{ github.event.inputs.task_batch }}" \
            -e BATCH_ID="${{ github.event.inputs.batch_id }}" \
            -e PROVIDER_INSTANCE_ID="${{ github.event.inputs.provider_id }}" \
            -e RABBITMQ_URL="${{ secrets.RABBITMQ_URL }}" \
            -e MINIO_ENDPOINT="${{ secrets.MINIO_ENDPOINT }}" \
            -e MINIO_ACCESS_KEY_ID="${{ secrets.MINIO_ACCESS_KEY_ID }}" \
            -e MINIO_SECRET_ACCESS_KEY="${{ secrets.MINIO_SECRET_ACCESS_KEY }}" \
            -e MINIO_USE_SSL="${{ secrets.MINIO_USE_SSL }}" \
            -e MINIO_BUCKET_NAME="${{ secrets.MINIO_BUCKET_NAME }}" \
            -v /tmp/attackatlas:/tmp/attackatlas \
            --name attackatlas-worker-${{ github.run_id }} \
            drkace/attackatlas-worker:latest



